### ISSUE TITLE
Is the "average" in Table 1 "micro-average" or "macro-average"?

### ISSUE THREAD

**Issue by ccsasuke** [princeton-nlp/EntityQuestions#1]
Hi,

As titled, is the reported overall performance in Table 1 a micro-average over all samples in the entire dataset regardless of relation types, or a macro-average taken across all relation types?

Thanks.

**Comment by cdsciavolino** [comment]
Hello,

Thanks for reading our paper! We use **macro-averaging** to report average results, specifically if we have two results:

Dataset A: 80 correct / 100 total = 80%
Dataset B: 30 correct / 50 total = 60%

The macro-average would be **70%** = (80% + 60%)/2, _not_ 73.3% = 110 / 150.

**Comment by ccsasuke** [comment]
Thanks for the clarification, @cdsciavolino!

That explains why the numbers I'm getting are slightly different from the paper.

Closing this issue for now, but I'm wondering whether micro-average makes more sense when using this dataset as a whole to report a single "overall" performance? Is this something you'd care to add to the Appendix for completeness?

**Comment by cdsciavolino** [comment]
Yeah that's a good point. When debating which to use, we landed on the idea that relation-level results would be more important than treating the entire EntityQ as an aggregate dataset. 

If I remember correctly when switching from micro-average to macro-average, the final results were very close (< 2% change in top-20 retrieval accuracy between the two across _all_ of our tables, typically < 1%). Since they were so close, we didn't report both in our paper; however, it might be good to add it somewhere in the appendix just for completeness. Thanks for the suggestion! :)
